keystore(
	name = 'app_keystore',
	store = 'debug.keystore',
	properties = 'debug.keystore.properties',
)

android_resource(
	name = 'res',
	res = 'src/main/res',
	package = 'com.github.promeg.doubanmovie',
	visibility = ['//app:src'],
)

android_library(
	name = 'src',
	srcs = glob(['src/main/java/**/*.java']),
	deps = [
		':res',
		'//common:src',
		'//model:src',
		'//.okbuck/app:all-jars',
		'//.okbuck/app:all-aars',
	],
	annotation_processors = [
		'org.antlr.v4.runtime.misc.RuleDependencyProcessor',
		'butterknife.internal.ButterKnifeProcessor',
		'org.antlr.v4.runtime.misc.NullUsageProcessor',
		'android.databinding.annotationprocessor.ProcessDataBinding',
		'com.hannesdorfmann.fragmentargs.processor.ArgProcessor',
		'dagger.internal.codegen.ComponentProcessor',
	],
	annotation_processor_deps = [
		'//common:src',
		'//model:src',
		'//.okbuck/app:all-jars',
		'//.okbuck/app:all-aars',
		'//.okbuck/annotation_processor_deps:all-jars',
		'//.okbuck/annotation_processor_deps:all-aars',
	],
)

android_binary(
	name = 'bin',
	manifest = 'src/main/AndroidManifest.xml',
	keystore = ':app_keystore',
	deps = [
		':res',
		':src',
	],
)

project_config(
	src_target = ':bin',
	src_roots = ['src/main/java'],
)

